# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import test_pb2 as test__pb2


class DrawStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Topology = channel.unary_unary(
                '/proto.Draw/Topology',
                request_serializer=test__pb2.TopologyRequest.SerializeToString,
                response_deserializer=test__pb2.TopologyReply.FromString,
                )


class DrawServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Topology(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DrawServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Topology': grpc.unary_unary_rpc_method_handler(
                    servicer.Topology,
                    request_deserializer=test__pb2.TopologyRequest.FromString,
                    response_serializer=test__pb2.TopologyReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.Draw', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Draw(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Topology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Draw/Topology',
            test__pb2.TopologyRequest.SerializeToString,
            test__pb2.TopologyReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
