# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x05proto\"\x1c\n\x0b\x44\x65stination\x12\r\n\x05Nodes\x18\x01 \x03(\x05\"\xb0\x01\n\x0fTopologyRequest\x12\x14\n\x0cSaveLocation\x18\x01 \x01(\t\x12\r\n\x05Total\x18\x02 \x01(\x05\x12\x10\n\x08\x43ontents\x18\x03 \x03(\t\x12(\n\x01G\x18\x04 \x03(\x0b\x32\x1d.proto.TopologyRequest.GEntry\x1a<\n\x06GEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.proto.Destination:\x02\x38\x01\"-\n\rTopologyReply\x12\n\n\x02Ok\x18\x01 \x01(\x08\x12\x10\n\x08\x46ilePath\x18\x02 \x01(\t2B\n\x04\x44raw\x12:\n\x08Topology\x12\x16.proto.TopologyRequest\x1a\x14.proto.TopologyReply\"\x00\x42\nZ\x08./;protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010./;proto'
  _TOPOLOGYREQUEST_GENTRY._options = None
  _TOPOLOGYREQUEST_GENTRY._serialized_options = b'8\001'
  _DESTINATION._serialized_start=21
  _DESTINATION._serialized_end=49
  _TOPOLOGYREQUEST._serialized_start=52
  _TOPOLOGYREQUEST._serialized_end=228
  _TOPOLOGYREQUEST_GENTRY._serialized_start=168
  _TOPOLOGYREQUEST_GENTRY._serialized_end=228
  _TOPOLOGYREPLY._serialized_start=230
  _TOPOLOGYREPLY._serialized_end=275
  _DRAW._serialized_start=277
  _DRAW._serialized_end=343
# @@protoc_insertion_point(module_scope)
